### ISSUE TITLE
Unicode Latin based character support

### ISSUE THREAD

**Issue by luizmendesalmeida** [jeyben/fixedformat4j#36]
Hi,

  I have a String which contains the character "Ç" (199 in the extended ASCII table).
  After parsing using the fixedformat4j, the String returned is something like "Ã"
  Can you help me?
  Thank you in advance.
  Best regards,

Luiz Almeida

**Comment by jeyben** [comment]
Hi Luiz,

Fixedformat4j only works on internal string representations and uses the native character encoding which is UTF-16 and contains your character.
My best guess is that you in some earlier stage has a conversion from bytes to String that causes the problem?

Maybe you can get som inspiration here:
http://stackoverflow.com/questions/5729806/encode-string-to-utf-8 <http://stackoverflow.com/questions/5729806/encode-string-to-utf-8>

Regards Jacob

**Comment by luizmendesalmeida** [comment]
Hi Jeyben,

  I apologize.
  The String returned is the same.
  Thank you.
  Regards,

Luiz Almeida
